In [180]:
data_path="for-rerecorded/training"

In [2]:
import os

In [3]:
def extract_features(file_path, mfcc=True, chroma=True, mel=True):
    audio, sample_rate = librosa.load(file_path, res_type='kaiser_fast')
    features = []
    if mfcc:
        mfccs = np.mean(librosa.feature.mfcc(y=audio, sr=sample_rate, n_mfcc=13), axis=1)
        features.extend(mfccs)
    if chroma:
        chroma = np.mean(librosa.feature.chroma_stft(y=audio, sr=sample_rate), axis=1)
        features.extend(chroma)
    if mel:
        mel = np.mean(librosa.feature.melspectrogram(y=audio, sr=sample_rate), axis=1)
        features.extend(mel)
    return features

In [4]:
import librosa
import numpy as np

In [5]:
def preprocess_dataset(data_path, labels):
    X = []
    y = []
    for label, folder in enumerate(labels):
        for filename in os.listdir(os.path.join(data_path, folder)):
            file_path = os.path.join(data_path, folder, filename)
            features = extract_features(file_path)
            X.append(features)
            y.append(label)
    return np.array(X), np.array(y)

In [6]:
labels = ["fake", "real"]

In [181]:
X, y = preprocess_dataset(data_path, labels)

In [182]:
from sklearn import preprocessing
lb = preprocessing.LabelBinarizer()
lb.fit(y)
y = lb.transform(y)
y = y.ravel()
print(y)

[0 0 0 ... 1 1 1]


In [183]:
import pandas as pd

In [184]:
df=pd.DataFrame(X)

In [185]:
X_train=df
   

In [186]:
y

array([0, 0, 0, ..., 1, 1, 1])

In [187]:
y_train=y

In [188]:
y_train

array([0, 0, 0, ..., 1, 1, 1])

In [189]:
data_path1="for-rerecorded/validation"

In [190]:
X1, y1 = preprocess_dataset(data_path1, labels)

In [191]:
from sklearn import preprocessing
lb1 = preprocessing.LabelBinarizer()
lb1.fit(y1)
y1 = lb.transform(y1)
y1 = y1.ravel()
print(y1)

[0 0 0 ... 1 1 1]


In [192]:
df1=pd.DataFrame(X1)

In [193]:
X_val=df1

In [195]:
X_val

0           1          2          3          4          5    \
0    -256.103912   98.469414  22.013477  52.473427 -19.976601  12.298381   
1    -300.186493   85.507095  20.787426  23.039135   2.667248  13.296325   
2    -157.332275  127.011574  -5.880052  43.091164 -18.972185  23.088911   
3    -276.085114  133.718170  27.578678  36.164024   1.329927  -0.267277   
4    -192.768143  116.761581   8.483458  39.969315 -18.644230  30.744694   
...          ...         ...        ...        ...        ...        ...   
2239 -170.995926  131.567947   4.367309  34.149075 -21.463945  19.826168   
2240 -276.502716  135.377914  10.197211  30.170574 -22.439758   6.364676   
2241 -203.477753  148.898331   3.335640  31.260937 -23.842278  10.415450   
2242 -278.188599  115.198441  15.943944  58.600094 -32.497604  25.483486   
2243 -184.132843  123.413986   4.582660  37.225571 -14.746784  16.139269   

            6          7         8          9    ...           143  \
0    -13.486473 -21.096678 -8.685554 -14.394847  ...  5.152135e-06   
1     -2.531562   1.466273 -0.258310  -9.347284  ...  1.021982e-05   
2    -13.768730 -11.887770 -1.636095 -30.187855  ...  3.442305e-06   
3     -0.001654 -10.962516 -5.820240 -11.429310  ...  7.507843e-06   
4    -20.441114  -3.995106 -4.845390 -27.480997  ...  1.530146e-05   
...         ...        ...       ...        ...  ...           ...   
2239  -9.597502  -8.316634  2.036535 -17.701063  ...  1.125740e-06   
2240 -15.692318 -24.409771  0.408411  -8.242374  ...  2.322224e-06   
2241 -18.996857 -33.429424 -3.545755 -22.562578  ...  4.251870e-07   
2242  -7.505641 -18.275711  4.931672 -24.413553  ...  1.841635e-06   
2243  -6.398055  -3.158630  1.546444 -15.234117  ...  3.705386e-06   

               144           145           146           147           148  \
0     4.850130e-06  4.598218e-06  4.396695e-06  4.228468e-06  4.089994e-06   
1     9.616067e-06  9.112850e-06  8.710424e-06  8.375203e-06  8.097788e-06   
2     3.239278e-06  3.070470e-06  2.935717e-06  2.823577e-06  2.731393e-06   
3     7.083778e-06  6.728964e-06  6.445035e-06  6.208104e-06  6.011506e-06   
4     1.439213e-05  1.363423e-05  1.303029e-05  1.252546e-05  1.211058e-05   
...            ...           ...           ...           ...           ...   
2239  1.064263e-06  1.011978e-06  9.696928e-07  9.341181e-07  9.046452e-07   
2240  2.187234e-06  2.074446e-06  1.984408e-06  1.909373e-06  1.847081e-06   
2241  3.897166e-07  3.615536e-07  3.396982e-07  3.221379e-07  3.080289e-07   
2242  1.731091e-06  1.639023e-06  1.565354e-06  1.504025e-06  1.453219e-06   
2243  3.489993e-06  3.310121e-06  3.166341e-06  3.046358e-06  2.947753e-06   

               149           150           151           152  
0     3.981520e-06  3.896523e-06  3.837688e-06  3.799962e-06  
1     7.881747e-06  7.711950e-06  7.595052e-06  7.520370e-06  
2     2.658706e-06  2.602187e-06  2.563323e-06  2.538142e-06  
3     5.857601e-06  5.736358e-06  5.654464e-06  5.600895e-06  
4     1.178593e-05  1.153132e-05  1.135512e-05  1.124303e-05  
...            ...           ...           ...           ...  
2239  8.812943e-07  8.630064e-07  8.504387e-07  8.422486e-07  
2240  1.798585e-06  1.760399e-06  1.734200e-06  1.717432e-06  
2241  2.970529e-07  2.887397e-07  2.830752e-07  2.793792e-07  
2242  1.413930e-06  1.382906e-06  1.361379e-06  1.347869e-06  
2243  2.869736e-06  2.808954e-06  2.767362e-06  2.740277e-06  

[2244 rows x 153 columns]

In [194]:
y_val=y1

In [196]:
from tensorflow.keras.models import Model,Sequential
from tensorflow.keras.layers import Input, Dense,Conv1D,MaxPool1D

In [198]:
import tensorflow as tf

In [199]:
model1 = tf.keras.Sequential([
    tf.keras.layers.LSTM(64, input_shape=(X_train.shape[1], 1))
    ,
    tf.keras.layers.Dropout(0.5),  # Add dropout layer
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dropout(0.5),  # Add dropout layer
    tf.keras.layers.Dense(1, activation='sigmoid', kernel_regularizer='l1')
])

In [200]:
model1.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])


In [201]:
model1.fit(X_train, y_train, epochs=10, batch_size=32, )

Epoch 1/10
319/319 [==============================] - 8s 10ms/step - loss: 0.7051 - accuracy: 0.6151
Epoch 2/10
319/319 [==============================] - 3s 9ms/step - loss: 0.6585 - accuracy: 0.6562
Epoch 3/10
319/319 [==============================] - 3s 10ms/step - loss: 0.5813 - accuracy: 0.7219
Epoch 4/10
319/319 [==============================] - 3s 9ms/step - loss: 0.4946 - accuracy: 0.7812
Epoch 5/10
319/319 [==============================] - 3s 9ms/step - loss: 0.4560 - accuracy: 0.7979
Epoch 6/10
319/319 [==============================] - 3s 9ms/step - loss: 0.4334 - accuracy: 0.8065
Epoch 7/10
319/319 [==============================] - 3s 9ms/step - loss: 0.4096 - accuracy: 0.8238
Epoch 8/10
319/319 [==============================] - 3s 9ms/step - loss: 0.3933 - accuracy: 0.8302
Epoch 9/10
319/319 [==============================] - 3s 9ms/step - loss: 0.3854 - accuracy: 0.8391
Epoch 10/10
319/319 [==============================] - 3s 9ms/step - loss: 0.3678 - accuracy: 0.85

In [219]:
model1.fit(X_train, y_train, epochs=10, batch_size=32,validation_data=(X_test,y_test) )

Epoch 1/10
319/319 [==============================] - 3s 10ms/step - loss: 0.1394 - accuracy: 0.9545 - val_loss: 0.7335 - val_accuracy: 0.7341
Epoch 2/10
319/319 [==============================] - 3s 10ms/step - loss: 0.1466 - accuracy: 0.9533 - val_loss: 0.6948 - val_accuracy: 0.7059
Epoch 3/10
319/319 [==============================] - 3s 10ms/step - loss: 0.1252 - accuracy: 0.9613 - val_loss: 0.5975 - val_accuracy: 0.7831
Epoch 4/10
319/319 [==============================] - 3s 10ms/step - loss: 0.1108 - accuracy: 0.9639 - val_loss: 1.3922 - val_accuracy: 0.6679
Epoch 5/10
319/319 [==============================] - 3s 10ms/step - loss: 0.1119 - accuracy: 0.9646 - val_loss: 1.4567 - val_accuracy: 0.5919
Epoch 6/10
319/319 [==============================] - 3s 10ms/step - loss: 0.1229 - accuracy: 0.9589 - val_loss: 0.5781 - val_accuracy: 0.7892
Epoch 7/10
319/319 [==============================] - 3s 10ms/step - loss: 0.1293 - accuracy: 0.9583 - val_loss: 0.9564 - val_accuracy: 0.7108

In [203]:
model1.fit(X_train, y_train, epochs=20, batch_size=64,validation_data=(X_val,y_val) )

Epoch 1/20
160/160 [==============================] - 3s 13ms/step - loss: 0.2265 - accuracy: 0.9199 - val_loss: 0.2569 - val_accuracy: 0.9042
Epoch 2/20
160/160 [==============================] - 2s 12ms/step - loss: 0.2189 - accuracy: 0.9242 - val_loss: 0.3068 - val_accuracy: 0.8899
Epoch 3/20
160/160 [==============================] - 2s 12ms/step - loss: 0.2102 - accuracy: 0.9263 - val_loss: 0.2603 - val_accuracy: 0.9055
Epoch 4/20
160/160 [==============================] - 2s 12ms/step - loss: 0.2133 - accuracy: 0.9288 - val_loss: 0.2492 - val_accuracy: 0.9131
Epoch 5/20
160/160 [==============================] - 2s 12ms/step - loss: 0.2087 - accuracy: 0.9303 - val_loss: 0.2619 - val_accuracy: 0.9024
Epoch 6/20
160/160 [==============================] - 2s 12ms/step - loss: 0.2053 - accuracy: 0.9297 - val_loss: 0.2203 - val_accuracy: 0.9176
Epoch 7/20
160/160 [==============================] - 2s 12ms/step - loss: 0.1964 - accuracy: 0.9351 - val_loss: 0.2227 - val_accuracy: 0.9180

In [204]:
model1.fit(X_train, y_train, epochs=30, batch_size=64,validation_data=(X_val,y_val) )

Epoch 1/30
160/160 [==============================] - 2s 13ms/step - loss: 0.1761 - accuracy: 0.9409 - val_loss: 0.2059 - val_accuracy: 0.9283
Epoch 2/30
160/160 [==============================] - 2s 12ms/step - loss: 0.1518 - accuracy: 0.9511 - val_loss: 0.1940 - val_accuracy: 0.9274
Epoch 3/30
160/160 [==============================] - 2s 13ms/step - loss: 0.1557 - accuracy: 0.9472 - val_loss: 0.2015 - val_accuracy: 0.9300
Epoch 4/30
160/160 [==============================] - 2s 13ms/step - loss: 0.1513 - accuracy: 0.9500 - val_loss: 0.2243 - val_accuracy: 0.9211
Epoch 5/30
160/160 [==============================] - 2s 12ms/step - loss: 0.1557 - accuracy: 0.9494 - val_loss: 0.1833 - val_accuracy: 0.9381
Epoch 6/30
160/160 [==============================] - 2s 12ms/step - loss: 0.1499 - accuracy: 0.9544 - val_loss: 0.2265 - val_accuracy: 0.9247
Epoch 7/30
160/160 [==============================] - 2s 12ms/step - loss: 0.1527 - accuracy: 0.9510 - val_loss: 0.1926 - val_accuracy: 0.9363

In [20]:
from sklearn.naive_bayes import GaussianNB

In [21]:
clf=GaussianNB()

In [23]:
clf.fit(X_train,y_train)

GaussianNB()

In [25]:
clf.score(X_train,y_train)

0.6515478056426333

In [26]:
clf.score(X_test,y_test)

0.6546345811051694

In [42]:
from sklearn.neighbors import NearestNeighbors

In [43]:
clf=NearestNeighbors()

In [44]:
clf.fit(X_train,y_train)

NearestNeighbors()

In [45]:
clf.score(X_train,y_train)

AttributeError: 'NearestNeighbors' object has no attribute 'score'

In [41]:
clf.score(X_test,y_test)

0.8284313725490197

In [46]:
from sklearn.preprocessing import StandardScaler

In [48]:
scaler=StandardScaler()

In [50]:
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [51]:
num_components = 3  # Adjust based on experimentation
covariance_type = 'full'  # Adjust based on experimentation
max_iterations = 100  

In [53]:
from sklearn.mixture import GaussianMixture

In [55]:
gmm = GaussianMixture(n_components=num_components, covariance_type=covariance_type, max_iter=max_iterations)

In [56]:
gmm.fit(X_train_scaled)

GaussianMixture(n_components=3)

In [57]:
y_pred = gmm.predict(X_test_scaled)

In [59]:
gmm.score(X_train_scaled,X_test_scaled)

-1.4344601679416915

In [61]:
from sklearn.metrics import accuracy_score

In [63]:
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")

Accuracy: 0.35962566844919786


In [64]:
from sklearn.svm import SVC

In [71]:
svm_classifier = SVC(kernel='rbf', C=1.0)


In [72]:
svm_classifier.fit(X_train_scaled, y_train)


SVC()

In [73]:
y_pred = svm_classifier.predict(X_test_scaled)


In [74]:
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")

Accuracy: 0.9532085561497327


In [75]:
svm_classifier.score(X_train_scaled,y_train)

0.9761951410658307

In [76]:
svm_classifier.score(X_test_scaled,y_test)

0.9532085561497327

In [77]:
from sklearn.neighbors import KNeighborsClassifier

In [78]:
# k-Nearest Neighbors (KNN)
knn_classifier = KNeighborsClassifier(n_neighbors=5)
knn_classifier.fit(X_train_scaled, y_train)
knn_pred = knn_classifier.predict(X_test_scaled)
knn_accuracy = accuracy_score(y_test, knn_pred)
print(f"KNN Accuracy: {knn_accuracy}")

KNN Accuracy: 0.9184491978609626


In [80]:
knn_classifier.score(X_train_scaled,y_train)

0.9441614420062696

In [81]:
knn_classifier.score(X_test_scaled,y_test)

0.9184491978609626

In [82]:
from sklearn.ensemble import HistGradientBoostingClassifier

In [148]:
clf = HistGradientBoostingClassifier(
    max_iter=1,
    max_depth=5,    # Control the maximum depth of each estimator
    learning_rate=0.2, 
    min_samples_leaf=10,  # Set a minimum number of samples required to be at a leaf node
    random_state=42
)

In [149]:
clf1.fit(X_train_scaled,y_train)

HistGradientBoostingClassifier()

In [150]:
clf1.score(X_train_scaled,y_train)

0.9964733542319749

In [151]:
clf1.score(X_test_scaled,y_test)

0.9625668449197861

In [95]:
a=clf1.predict(X_test_scaled)

In [96]:

gb_accuracy = accuracy_score(y_test, a)
print(f"gb Accuracy: {knn_accuracy}")

gb Accuracy: 0.9184491978609626


In [205]:
data_path2="for-rerecorded/testing"

In [155]:
labels = ["fake", "real"]

In [156]:
def preprocess_dataset(data_path, labels):
    X = []
    y = []
    for label, folder in enumerate(labels):
        for filename in os.listdir(os.path.join(data_path, folder)):
            file_path = os.path.join(data_path, folder, filename)
            features = extract_features(file_path)
            X.append(features)
            y.append(label)
    return np.array(X), np.array(y)

In [206]:
X2, y2 = preprocess_dataset(data_path2, labels)

In [208]:
from sklearn import preprocessing
lb = preprocessing.LabelBinarizer()
lb.fit(y2)
y2 = lb.transform(y2)
y2 = y2.ravel()
print(y2)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 

In [159]:
import pandas as pd

In [209]:
df=pd.DataFrame(X2)

In [210]:
df

0           1          2          3          4          5    \
0   -158.425888  143.737640  -3.421895  23.124899 -15.193885  24.818220   
1   -162.403244  144.773376   3.088728  29.386974 -12.531352  20.539282   
2   -165.431015  136.146378  -3.314423  42.388786 -16.870707  23.915314   
3   -146.756409  144.073120  -3.665487  30.452641 -19.225594  21.058481   
4   -171.529465  160.476868 -13.078272  26.888058 -20.511671  18.870352   
..          ...         ...        ...        ...        ...        ...   
811 -206.659378  121.433647  -0.320798  68.330048 -14.853692  16.166746   
812 -223.937439  138.260895  13.372982  30.227598 -34.127480  32.890003   
813 -191.158951  137.332672  11.960568  50.376057 -27.046873  18.494043   
814 -169.291580  144.783615  -1.863288  44.370647 -35.544731   9.208752   
815 -183.172272  161.067947   2.489607  47.417374 -20.204407   4.453347   

           6          7          8          9    ...           143  \
0   -10.542620  -9.289985  -0.849831 -19.399073  ...  1.712595e-06   
1    -9.818403  -7.625255  -5.300449 -23.327536  ...  4.567614e-06   
2   -18.782120 -14.293229  -8.698584 -27.430391  ...  1.363575e-06   
3    -9.573334  -6.169008  -3.430728 -23.158026  ...  5.725443e-06   
4   -24.506311 -18.751568 -10.306947 -26.929226  ...  1.540792e-05   
..         ...        ...        ...        ...  ...           ...   
811  -8.066371 -22.559032 -17.679024 -24.006382  ...  5.965944e-06   
812 -16.404003 -16.231743   0.697566 -18.107117  ...  9.968337e-06   
813  -9.001764 -17.273994 -22.594812 -22.798145  ...  7.927000e-06   
814 -22.272167 -15.503508  -2.217409 -21.822470  ...  6.891764e-07   
815  -4.562777 -17.137804 -22.915905 -17.502466  ...  7.241126e-06   

              144           145           146           147           148  \
0    1.609247e-06  1.523417e-06  1.454864e-06  1.397858e-06  1.350945e-06   
1    4.308221e-06  4.090845e-06  3.916583e-06  3.770861e-06  3.651247e-06   
2    1.289662e-06  1.227146e-06  1.176609e-06  1.134309e-06  1.099032e-06   
3    5.257770e-06  4.878174e-06  4.577393e-06  4.331780e-06  4.132319e-06   
4    1.459046e-05  1.390033e-05  1.334531e-05  1.287893e-05  1.249118e-05   
..            ...           ...           ...           ...           ...   
811  5.622901e-06  5.335919e-06  5.106075e-06  4.914223e-06  4.755546e-06   
812  9.239613e-06  8.647280e-06  8.179822e-06  7.797359e-06  7.486668e-06   
813  7.510717e-06  7.160212e-06  6.878980e-06  6.643033e-06  6.445533e-06   
814  6.448542e-07  6.085008e-07  5.798059e-07  5.560444e-07  5.369048e-07   
815  6.820836e-06  6.470197e-06  6.189679e-06  5.955989e-06  5.762568e-06   

              149           150           151           152  
0    1.314226e-06  1.285638e-06  1.265734e-06  1.253083e-06  
1    3.556295e-06  3.482241e-06  3.431439e-06  3.398399e-06  
2    1.071235e-06  1.049495e-06  1.034390e-06  1.024666e-06  
3    3.979466e-06  3.861586e-06  3.777597e-06  3.728496e-06  
4    1.218819e-05  1.194861e-05  1.178375e-05  1.167697e-05  
..            ...           ...           ...           ...  
811  4.631253e-06  4.533654e-06  4.466728e-06  4.423576e-06  
812  7.245923e-06  7.058823e-06  6.929414e-06  6.847427e-06  
813  6.292208e-06  6.170346e-06  6.086780e-06  6.032947e-06  
814  5.214650e-07  5.096961e-07  5.018591e-07  4.966183e-07  
815  5.611489e-06  5.492740e-06  5.411409e-06  5.359071e-06  

[816 rows x 153 columns]

In [211]:
X_test=df
   

In [212]:
y_test=y2

In [213]:
X_test

0           1          2          3          4          5    \
0   -158.425888  143.737640  -3.421895  23.124899 -15.193885  24.818220   
1   -162.403244  144.773376   3.088728  29.386974 -12.531352  20.539282   
2   -165.431015  136.146378  -3.314423  42.388786 -16.870707  23.915314   
3   -146.756409  144.073120  -3.665487  30.452641 -19.225594  21.058481   
4   -171.529465  160.476868 -13.078272  26.888058 -20.511671  18.870352   
..          ...         ...        ...        ...        ...        ...   
811 -206.659378  121.433647  -0.320798  68.330048 -14.853692  16.166746   
812 -223.937439  138.260895  13.372982  30.227598 -34.127480  32.890003   
813 -191.158951  137.332672  11.960568  50.376057 -27.046873  18.494043   
814 -169.291580  144.783615  -1.863288  44.370647 -35.544731   9.208752   
815 -183.172272  161.067947   2.489607  47.417374 -20.204407   4.453347   

           6          7          8          9    ...           143  \
0   -10.542620  -9.289985  -0.849831 -19.399073  ...  1.712595e-06   
1    -9.818403  -7.625255  -5.300449 -23.327536  ...  4.567614e-06   
2   -18.782120 -14.293229  -8.698584 -27.430391  ...  1.363575e-06   
3    -9.573334  -6.169008  -3.430728 -23.158026  ...  5.725443e-06   
4   -24.506311 -18.751568 -10.306947 -26.929226  ...  1.540792e-05   
..         ...        ...        ...        ...  ...           ...   
811  -8.066371 -22.559032 -17.679024 -24.006382  ...  5.965944e-06   
812 -16.404003 -16.231743   0.697566 -18.107117  ...  9.968337e-06   
813  -9.001764 -17.273994 -22.594812 -22.798145  ...  7.927000e-06   
814 -22.272167 -15.503508  -2.217409 -21.822470  ...  6.891764e-07   
815  -4.562777 -17.137804 -22.915905 -17.502466  ...  7.241126e-06   

              144           145           146           147           148  \
0    1.609247e-06  1.523417e-06  1.454864e-06  1.397858e-06  1.350945e-06   
1    4.308221e-06  4.090845e-06  3.916583e-06  3.770861e-06  3.651247e-06   
2    1.289662e-06  1.227146e-06  1.176609e-06  1.134309e-06  1.099032e-06   
3    5.257770e-06  4.878174e-06  4.577393e-06  4.331780e-06  4.132319e-06   
4    1.459046e-05  1.390033e-05  1.334531e-05  1.287893e-05  1.249118e-05   
..            ...           ...           ...           ...           ...   
811  5.622901e-06  5.335919e-06  5.106075e-06  4.914223e-06  4.755546e-06   
812  9.239613e-06  8.647280e-06  8.179822e-06  7.797359e-06  7.486668e-06   
813  7.510717e-06  7.160212e-06  6.878980e-06  6.643033e-06  6.445533e-06   
814  6.448542e-07  6.085008e-07  5.798059e-07  5.560444e-07  5.369048e-07   
815  6.820836e-06  6.470197e-06  6.189679e-06  5.955989e-06  5.762568e-06   

              149           150           151           152  
0    1.314226e-06  1.285638e-06  1.265734e-06  1.253083e-06  
1    3.556295e-06  3.482241e-06  3.431439e-06  3.398399e-06  
2    1.071235e-06  1.049495e-06  1.034390e-06  1.024666e-06  
3    3.979466e-06  3.861586e-06  3.777597e-06  3.728496e-06  
4    1.218819e-05  1.194861e-05  1.178375e-05  1.167697e-05  
..            ...           ...           ...           ...  
811  4.631253e-06  4.533654e-06  4.466728e-06  4.423576e-06  
812  7.245923e-06  7.058823e-06  6.929414e-06  6.847427e-06  
813  6.292208e-06  6.170346e-06  6.086780e-06  6.032947e-06  
814  5.214650e-07  5.096961e-07  5.018591e-07  4.966183e-07  
815  5.611489e-06  5.492740e-06  5.411409e-06  5.359071e-06  

[816 rows x 153 columns]

In [214]:
y_test

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [215]:
model1.evaluate(X_test,y_test)

26/26 [==============================] - 0s 13ms/step - loss: 1.3843 - accuracy: 0.6324


[1.3842661380767822, 0.6323529481887817]

In [217]:
y_pred=model.predict(X_test)

In [218]:
from sklearn.metrics import confusion_matrix, classification_report

# Make predictions on the test set
y_pred = model.predict(X_test)

# Convert probabilities to class labels
y_pred_classes = (y_pred > 0.5).astype(int)

# Create a confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred_classes)

print("Confusion Matrix:")
print(conf_matrix)

# Generate a classification report
print("Classification Report:")
print(classification_report(y_test, y_pred_classes))


Confusion Matrix:
[[210 198]
 [ 60 348]]
Classification Report:
              precision    recall  f1-score   support

           0       0.78      0.51      0.62       408
           1       0.64      0.85      0.73       408

    accuracy                           0.68       816
   macro avg       0.71      0.68      0.67       816
weighted avg       0.71      0.68      0.67       816



In [167]:
import joblib

In [168]:
model=joblib.load('deepfakevoiceperhistboostinggrediant.h5')

In [169]:
model

HistGradientBoostingClassifier()

In [173]:
from sklearn.metrics import confusion_matrix, classification_report

# Make predictions on the test set
y_pred = model.predict(X_test)

# Convert probabilities to class labels
y_pred_classes = (y_pred > 0.5).astype(int)

# Create a confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred_classes)

print("Confusion Matrix:")
print(conf_matrix)

# Generate a classification report
print("Classification Report:")
print(classification_report(y_test, y_pred_classes))


Confusion Matrix:
[[210 198]
 [ 60 348]]
Classification Report:
              precision    recall  f1-score   support

           0       0.78      0.51      0.62       408
           1       0.64      0.85      0.73       408

    accuracy                           0.68       816
   macro avg       0.71      0.68      0.67       816
weighted avg       0.71      0.68      0.67       816

